### ISSUE TITLE
How to get a Language reference in a test

### ISSUE THREAD

**Issue by Gauteab** [tree-sitter/haskell-tree-sitter#289] opened 2020-09-04 14:31 UTC
If I try to  `import TreeSitter.Haskell` in `Example.hs` I get
````
test/TreeSitter/Example.hs:15:1: error:
    Could not load module ‘TreeSitter.Haskell’
    It is a member of the hidden package ‘tree-sitter-haskell-0.3.0.1’.
    Perhaps you need to add ‘tree-sitter-haskell’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘tree-sitter-haskell-0.3.0.1’.
    Perhaps you need to add ‘tree-sitter-haskell’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
````

Adding `tree-sitter-haskell` to `build-depends` in `test-suite: test` I get

```
cabal: Could not resolve dependencies:
[__0] trying: tree-sitter-0.9.0.2 (user goal)
[__1] trying: tree-sitter-haskell-0.3.0.1 (user goal)
[__2] trying: tree-sitter-haskell:+build-examples
[__3] rejecting: tree-sitter:*test (cyclic dependencies; conflict set:
tree-sitter, tree-sitter-haskell)
[__1] rejecting: tree-sitter-haskell-0.3.0.0, tree-sitter-haskell-0.2.0.1,
tree-sitter-haskell-0.2.0.0, tree-sitter-haskell-0.1.0.0 (constraint from user
target requires ==0.3.0.1)
[__1] fail (backjumping, conflict set: tree-sitter, tree-sitter-haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: tree-sitter, tree-sitter-haskell
```

Trying to get something running so I can try implementing Queries.

I'm not very experienced with cabal.

**Comment by patrickt** [comment] 2020-09-08 14:01
Have you added the `tree-sitter-haskell` package as a dependency in the [test suite stanza](https://github.com/tree-sitter/haskell-tree-sitter/blob/master/tree-sitter/tree-sitter.cabal#L76-L86)?

**Comment by Gauteab** [comment] 2020-09-08 22:05
Yes, that's when I got the second error.

**Comment by patrickt** [comment] 2020-09-09 15:50
Ah, I see. The problem is here?

```
[__2] trying: tree-sitter-haskell:+build-examples
[__3] rejecting: tree-sitter:*test (cyclic dependencies; conflict set:
tree-sitter, tree-sitter-haskell)
```

You’re attempting to import `tree-sitter-haskell` from the `tree-sitter` package itself, which is a problem in that `tree-sitter-haskell` depends on `tree-sitter`. You can either move your examples to the `tree-sitter-haskell` package (which has an example; check `Demo.hs`) or you can start a whole new package and import from there.

By the way, please be aware that the `tree-sitter-haskell` grammar is in flux, and though it parses a lot of GHC Haskell it doesn’t handle everything correctly and doesn’t implement all language extensions (we need BlockArguments support, for one). Feel free to file bugs [here](https://github.com/tree-sitter/tree-sitter-haskell) should you find them.

**Comment by Gauteab** [comment] 2020-09-10 11:54
Thank you!

I have made some progress with queries. Hopefully I'll be able to finish it

**Comment by patrickt** [comment] 2020-09-10 14:46
Awesome. I’m going to close this for now, but feel free to leave comments in the thread should the need arise.

**Closed by patrickt** 2020-09-10 14:46 UTC
